get qti-telephony-common.jar from tissot
07-12 08:32:32.831  3241  3241 D AndroidRuntime: Shutting down VM
07-12 08:32:32.832  3241  3241 E AndroidRuntime: FATAL EXCEPTION: main
07-12 08:32:32.832  3241  3241 E AndroidRuntime: Process: com.android.phone, PID: 3241
07-12 08:32:32.832  3241  3241 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/BuildExt;
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiSubscriptionController.handleDataPreference(QtiSubscriptionController.java:532)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiSubscriptionController.updateUserPreferences(QtiSubscriptionController.java:426)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiSubscriptionInfoUpdater.updateSubscriptionInfoByIccId(QtiSubscriptionInfoUpdater.java:219)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.android.internal.telephony.SubscriptionInfoUpdater.handleSimAbsentOrError(SubscriptionInfoUpdater.java:614)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiSubscriptionInfoUpdater.handleSimAbsentOrError(QtiSubscriptionInfoUpdater.java:199)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.android.internal.telephony.SubscriptionInfoUpdater.handleMessage(SubscriptionInfoUpdater.java:361)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiSubscriptionInfoUpdater.handleMessage(QtiSubscriptionInfoUpdater.java:125)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.BuildExt" on path: DexPathList[[zip file "/system/framework/qti-telephony-common.jar"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-12 08:32:32.832  3241  3241 E AndroidRuntime: 	... 13 more

Change-Id: Ib5e539f4d346e0f4925387670f559db31900efe8